const Grok = require("groq-sdk").default;

const groq = new Grok({
  apiKey: process.env.GROQ_API_KEY,
});



const generateJsonFromLLM = async ({ prompt, maxTokens }) => {
  const response = await groq.chat.completions.create({
    model: "llama-3.1-8b-instant",
    messages: [
      { role: "system", content: "You are a strict JSON generator. Follow instructions exactly." },
      { role: "user", content: prompt }
    ],
    temperature: 0.3,
    max_tokens: maxTokens,
    response_format: { type: "json_object" },
  });


  const raw = response?.choices?.[0]?.message?.content;
  if (!raw) {
    throw new Error("Empty response from LLM");
  }

  try {
    return JSON.parse(raw.trim());
  } catch (err) {
    console.error("RAW LLM OUTPUT:", raw);
    throw new Error("Invalid JSON generated by LLM");
  }
};





const generateTextFromLLM = async ({ prompt, maxTokens }) => {
  const response = await groq.chat.completions.create({
    model: "llama-3.1-8b-instant",
    messages: [
      { role: "system", content: "You are a helpful assistant and a translator." },
      { role: "user", content: prompt }
    ],
    temperature: 0.5,
    max_tokens: maxTokens,
  });

  const raw = response?.choices?.[0]?.message?.content;
  if (!raw) {
    throw new Error("Empty response from LLM");
  }

  return raw.trim();
};






const generateTopicAndDesciptionService = async ({ prompt }) => {
  const data = await generateJsonFromLLM({ prompt, maxTokens: 250 });

  // Safety fallback if LLM misses the description or it's empty
  if (!data.description || data.description.trim() === "") {
    data.description = `I want to learn more about ${data.topicName || "this topic"} in depth.`;
  }

  // Ensure topicName isn't missing either
  if (!data.topicName || data.topicName.trim() === "") {
    data.topicName = "Custom Learning Course";
  }

  return data;
};




const generateOutlineService = async ({ prompt }) => {
  return generateJsonFromLLM({ prompt, maxTokens: 3800 });
};



const generateLessonService = async (prompt) => {
  return generateJsonFromLLM({ prompt, maxTokens: 4500 });
};



const generateYouTubeQueryService = async (prompt) => {
  return generateJsonFromLLM({ prompt, maxTokens: 200 });
};



const generateHinglishService = async (prompt) => {
  return generateTextFromLLM({ prompt, maxTokens: 4500 });
};



module.exports = {
  generateOutlineService,
  generateLessonService,
  generateTopicAndDesciptionService,
  generateYouTubeQueryService,
  generateHinglishService
};