const {
  findById,
  saveCourseOutlineToDB,
  findRecentCoursesByUser,
  findLessonForUser,
  checkLessonExistsForUser,
  saveLesson,
  saveHinglishContent,
  searchVectorDB,
  getLesson,
} = require("../repository/course.repository");

const { addLessonToLazyLessonGenerationQueue } = require("../utils/helper");

const { getYouTubeVideos } = require("../repository/YouTube.repository");

const mongoose = require("mongoose");
const Course = require("../models/course");
const Module = require("../models/module");
const Lesson = require("../models/lesson");

const { generateEmbedding } = require("./ai_embeding_service");
const {
  generateOutlineService,
  intentGenerationService,
  generateLessonService,
} = require("./course.generate.service");




const saveCourseOutlineToDBService = async (
  outline,
  userId,
  intent,
  embedding,
  prompt,
) => {
  if (!outline?.course || !outline?.modules) {
    throw new Error("Invalid course outline structure");
  }

  const session = await mongoose.startSession();

  try {
    session.startTransaction();

    const { course, modules } = outline;

    //-------------------------------------
    // Create Course
    //-------------------------------------

    const [createdCourse] = await Course.create(
      [
        {
          title: course.title || "Untitled Course",

          description: course.description || "Course generated by AI",

          userId,

          learningIntent: {
            topic: intent.topic,
            goal: intent.goal,
            level: intent.level,
            targetRole: intent.targetRole,

            canonicalQuery: intent.canonicalQuery,

            confidence: intent.confidence,
          },

          embedding,

          generatedFromPrompt: prompt,
        },
      ],
      { session },
    );

    //-------------------------------------
    // Create Modules + Lessons
    //-------------------------------------

    for (const moduleData of modules) {
      const [createdModule] = await Module.create(
        [
          {
            moduleIndex: moduleData.moduleIndex,

            title: moduleData.title,

            description: moduleData.description,

            course: createdCourse._id,
          },
        ],
        { session },
      );

      //-------------------------------------
      // Build Lessons
      //-------------------------------------

      const lessonDocuments = moduleData.lessons.map((lesson) => ({
        lessonIndex: lesson.lessonIndex,

        title: lesson.title,

        realWorldProblem: lesson.realWorldProblem,

        learnerTakeaway: lesson.learnerTakeaway,

        completionCriteria: lesson.completionCriteria,

        briefDescription: lesson.briefDescription,

        module: createdModule._id,

        content: null,

        isGenerated: "PENDING",
      }));

      if (lessonDocuments.length > 0) {
        await Lesson.insertMany(lessonDocuments, { session });
      }
    }

    await session.commitTransaction();

    return createdCourse;
  } catch (error) {
    await session.abortTransaction();

    throw error;
  } finally {
    session.endSession();
  }

  return createdCourse;
};

const getRecentCoursesService = async (userId) => {
  console.log("\n\n\n\n s ***************************\n\n\n");

  if (!userId) {
    throw new Error("User ID is required");
  }

  const courses = await findRecentCoursesByUser(userId);

  return courses.map((course) => ({
    courseId: course._id,
    courseTitle: course.title,
    courseDescription: course.description,
  }));
};

const getUserCourseService = async (userId) => {
  if (!userId) {
    throw new Error("User ID is required");
  }

  const courses = await findRecentCoursesByUser(userId, 7);

  return courses.map((course) => ({
    courseId: course._id,
    courseTitle: course.title,
    courseDescription: course.description,
  }));
};

const stream = (res, message, extra = {}) => {
  res.write(
    `data: ${JSON.stringify({
      message,
      ...extra,
    })}\n\n`,
  );
};


// Send course via SSE
const sendCourse = (res, course) => {
  try {
    if (!course) {
      res.write(
        `data: ${JSON.stringify({
          type: "ERROR",
          message: "Course data not found",
        })}\n\n`,
      );
      return res.end();
    }

    res.write(
      `data: ${JSON.stringify({
        type: "SUCCESS",
        message: "Course generated successfully",
        course: {
          _id: course._id,
          title: course.title,
          description: course.description,
          learningIntent: course.learningIntent,
        },
      })}\n\n`,
    );

    return res.end();
  } catch (error) {
    console.error("sendCourse error:", error);
    res.write(
      `data: ${JSON.stringify({
        type: "ERROR",
        message: "Error sending course data",
      })}\n\n`,
    );
    return res.end();
  }
};



const generateCourseFlow = async (prompt, res, userId) => {
  try {
    if (!prompt || !userId) {
      stream(res, "Error: Missing prompt or userId");
      return res.end();
    }

    stream(res, "🎯 Extracting learning intent from your prompt...");

    const intent = await intentGenerationService({ prompt });

    if (!intent || !intent.canonicalQuery) {
      throw new Error("Failed to extract learning intent");
    }

    stream(res, "🔍 Generating semantic embedding...");

    const embedding = await generateEmbedding(intent.canonicalQuery);

    stream(res, "🔎 Searching for similar existing courses...");

    const similar = await searchVectorDB(embedding, intent);

    if (similar && similar.score > 0.85 && similar._id) {
      console.log(
        `✅ Found existing course with ${(similar.score * 100).toFixed(1)}% similarity`,
      );

      stream(
        res,
        `✨ Found a similar course (${(similar.score * 100).toFixed(1)}% match)! Returning existing course...`,
      );

      // Get the full course with modules/lessons populated
      return sendCourse(res, similar);
    }

    console.log(
      `❌ No similar course found (best match: ${similar ? (similar.score * 100).toFixed(1) : 0}%)`,
    );

    stream(
      res,
      "🚀 No similar course found. Generating brand new course structure...",
    );

    const course = await generateOutlineService(intent);

    if (!course) {
      throw new Error("Failed to create new course");
    }

    stream(res, "✅ Course generated successfully!");

    const savedCourse = saveCourseOutlineToDBService(
      course,
      userId,
      intent,
      embedding,
      prompt,
    );

    stream(res, "✅ Course saved successfully!");

    // await addLessonToLazyLessonGenerationQueue(savedCourse._id);

    return sendCourse(res, savedCourse);

  } catch (error) {
    console.error("❌ generateCourseFlow error:", error);

    res.write(
      `data: ${JSON.stringify({
        type: "ERROR",
        message: error.message || "Course generation failed",
        error: process.env.NODE_ENV === "development" ? error.stack : undefined,
      })}\n\n`,
    );

    return res.end();
  }
};

const getCourseDetailsWithProgressService = async (courseId, userId) => {
  if (!courseId || !userId) {
    throw new Error("Course ID and User ID are required");
  }

  const course = await findById(courseId); // now populates modules + lessons
  if (!course) {
    throw new Error("Course not found");
  }

  // Find first incomplete module
  let currentModuleIndex = 1;
  let currentLessonIndex = 1;

  let found = false;
  for (const mod of course.modules) {
    for (const lesson of mod.lessons) {
      if (!lesson.isCompleted) {
        currentModuleIndex = mod.moduleIndex;
        currentLessonIndex = lesson.lessonIndex;
        found = true;
        break;
      }
    }
    if (found) break;
  }

  // All lessons completed — point to the last lesson
  if (!found && course.modules.length > 0) {
    const lastMod = course.modules[course.modules.length - 1];
    currentModuleIndex = lastMod.moduleIndex;
    const lastLesson = lastMod.lessons[lastMod.lessons.length - 1];
    currentLessonIndex = lastLesson ? lastLesson.lessonIndex : 1;
  }

  return {
    course,
    progress: {
      currentModule: currentModuleIndex,
      currentLesson: currentLessonIndex,
    },
  };
};

const completeLessonService = async ({ moduleId, lessonId }) => {
  if (!moduleId || !lessonId) {
    throw new Error("Missing required parameters");
  }

  const course = await markLessonCompleted({
    moduleId,
    lessonId,
  });

  if (!course) {
    throw new Error("Course not found");
  }

  return {
    message: "Lesson marked as completed",
  };
};

const getLessonContentService = async ({ moduleId, lessonId }) => {
  const result = await findLessonForUser({
    moduleId,
    lessonId,
  });

  if (!result) {
    throw new Error("Lesson not found");
  }

  const lesson = result;

  return {
    lesson: {
      title: lesson.title,
      description: lesson.briefDescription,
      ...lesson.content,
      hinglishContent: lesson.hinglishContent,
      isCompleted: lesson.isCompleted,
      lessonIndex: lesson.lessonIndex,
      module: lesson.module,
      _id: lesson._id,
    },
    module: {
      title: "Learning Module", // Fallback title
      moduleIndex: lesson.moduleIndex || 0,
    },
  };
};


const getYouTubeVideosService = async (query) => {
  try {
    return await getYouTubeVideos(query);
  } catch (error) {
    throw error;
  }
};


const checkLessonExistsService = async (lessonId) => {
  const exists = await checkLessonExistsForUser(lessonId);
  return { exists };
};


const saveLessonService = async (moduleId, lessonId, lesson) => {
  let actualLesson = lesson;

  if (!moduleId || !lessonId || !actualLesson) {
    throw new Error("Missing required parameters for saving lesson");
  }

  let lessonPayload = {};

  if (actualLesson && actualLesson.data) {
    lessonPayload.content = actualLesson.data;
  } else if (actualLesson && actualLesson.content) {
    lessonPayload = actualLesson;
  } else {
    lessonPayload.content = actualLesson;
  }

  const savedLesson = await saveLesson(moduleId, lessonId, lessonPayload);

  if (!savedLesson) {
    throw new Error("Failed to save lesson (Course/Module/Lesson not found)");
  }

  return savedLesson;
};

const saveHinglishContentService = async (moduleId, lessonId, content) => {
  if (!moduleId || !lessonId || !content) {
    throw new Error("Missing parameters for saving Hinglish content");
  }
  return await saveHinglishContent(moduleId, lessonId, content);
};



const lessonGenerationFlow = async (lessonId, res) => {
  try {
    if (!lessonId) {
      stream(res, "❌ Error: Lesson ID is missing");
      return res.end();
    }



    stream(res, "🔍 Fetching lesson details...");

    // Fetch lesson from DB
    const lesson = await getLesson(lessonId);
    if (!lesson) {
      throw new Error("Lesson not found");
    }



    // Check if lesson already generated
    if (lesson.isGenerated === "GENERATED" && lesson.content) {
      stream(res, "✅ Lesson already generated. Retrieving from cache...");
      stream(
        res,
        "✅ Lesson loaded successfully!",
        {
          type: "SUCCESS",
          lesson: {
            _id: lesson._id,
            title: lesson.title,
            description: lesson.briefDescription,
            content: lesson.content,
            youtubeQuery: lesson.youtubeQuery,
            isGenerated: lesson.isGenerated,
          },
        }
      );
      return res.end();
    }



    stream(res, "🤖 Generating lesson content...");

    // Prepare lesson data for generation
    const lessonData = {
      title: lesson.title,
      realWorldProblem: lesson.realWorldProblem,
      learnerTakeaway: lesson.learnerTakeaway,
      completionCriteria: lesson.completionCriteria,
      briefDescription: lesson.briefDescription,
    };



    // Generate lesson content
    const genLesson = await generateLessonService(lessonData);
    if (!genLesson) {
      throw new Error("Failed to generate lesson content");
    }



    stream(res, "📹 Generating YouTube query and fetching videos...");

    // Fetch YouTube videos
    const videos = await getYouTubeVideosService(
      genLesson.youtubeQuery?.query || lesson.title
    );

    console.log(`\n\n\n printing videos : ${JSON.stringify(videos)} \n\n\n`);

    // Prepare final lesson object
    const finalLesson = {
      content: genLesson.data || genLesson,
      youtubeQuery: {
        query: genLesson.youtubeQuery?.query || lesson.title,
        videos: videos || [],
      },
      isGenerated: "GENERATED",
    };

    stream(res, "💾 Saving lesson to database...");

    // Save lesson with content and videos
    const savedLesson = await saveLessonService(
      lesson.module,
      lessonId,
      finalLesson
    );
    if (!savedLesson) {
      throw new Error("Failed to save lesson to database");
    }

    stream(
      res,
      "✅ Lesson generated and saved successfully!",
      {
        type: "SUCCESS",
        lesson: {
          _id: savedLesson._id,
          title: savedLesson.title,
          description: savedLesson.briefDescription,
          content: savedLesson.content,
          youtubeQuery: savedLesson.youtubeQuery,
          isGenerated: savedLesson.isGenerated,
        },
      }
    );

    return res.end();
  } catch (error) {
    console.error("❌ lessonGenerationFlow error:", error);
    res.write(
      `data: ${JSON.stringify({
        type: "ERROR",
        message: error.message || "Lesson generation failed",
        error:
          process.env.NODE_ENV === "development" ? error.stack : undefined,
      })}\n\n`
    );
    return res.end();
  }
};



module.exports = {
  saveCourseOutlineToDBService,
  getRecentCoursesService,
  getCourseDetailsWithProgressService,
  completeLessonService,
  getLessonContentService,
  checkLessonExistsService,
  saveLessonService,
  getYouTubeVideosService,
  saveHinglishContentService,
  getUserCourseService,
  generateCourseFlow,
  lessonGenerationFlow,
};
