const Grok = require("groq-sdk").default;

const groq = new Grok({
  apiKey: process.env.GROQ_API_KEY,
});

const generateJsonFromLLM = async ({ prompt, maxTokens }) => {



  const response = await groq.chat.completions.create({
    model: "llama-3.1-8b-instant",
    messages: [
      { role: "system", content: "You are a strict JSON generator. Follow instructions exactly." },
      { role: "user", content: prompt }
    ],
    temperature: 0.3,
    max_tokens: maxTokens,
    response_format: { type: "json_object" },
  });

  const raw = response?.choices?.[0]?.message?.content;
  if (!raw) {
    throw new Error("Empty response from LLM");
  }


  try {
    return JSON.parse(raw.trim());
  } catch (err) {
    console.error("RAW LLM OUTPUT:", raw);
    throw new Error("Invalid JSON generated by LLM");
  }
};


const generateTopicAndDesciptionService = async ({ prompt }) => {

  return generateJsonFromLLM({ prompt, maxTokens: 1000 });
};

const generateOutlineService = async ({ prompt }) => {
  return generateJsonFromLLM({ prompt, maxTokens: 5000 });
};


const generateLessonService = async (prompt) => {
  return generateJsonFromLLM({ prompt, maxTokens: 8000 });
};


const generateYouTubeQueryService = async (prompt) => {



  return generateJsonFromLLM({ prompt, maxTokens: 3000 });
};


module.exports = { generateOutlineService, generateLessonService, generateTopicAndDesciptionService, generateYouTubeQueryService };