const { findById, saveCourseOutlineToDB, findRecentCoursesByUser,
  findLessonForUser,
  checkLessonExistsForUser,
  saveLesson,
  saveHinglishContent,
} = require("../repository/course.repository");

const { getYouTubeVideos } = require("../repository/YouTube.repository");


const saveCourseOutlineToDBService = async (outline, userId) => {

  if (!outline?.course || !outline?.modules) {
    throw new Error("Invalid course outline structure");
  }

  const { course, modules } = outline;



  const courseDocument = {
    title: course.title || "Untitled Course",
    description: course.description || "Course generated by AI",
    courseObjective: course.courseObjective || "Master the topic",
    tags: Array.isArray(course.tags) ? course.tags : [], // Bug Fix 3: forward tags
    userId,
    modules: modules.map((m, idx) => ({
      moduleIndex: m.moduleIndex || idx + 1,
      title: m.title || `Module ${idx + 1}`,
      description: m.description || `Learning module for ${m.title || "the course"}`,
      lessons: (m.lessons || []).map((l, lIdx) => ({
        lessonIndex: l.lessonIndex || lIdx + 1,
        title: l.title || `Lesson ${lIdx + 1}`,
        briefDescription: l.description || l.briefDescription || "Lesson content",
      })),
    })),
  };

  return await saveCourseOutlineToDB(courseDocument);
};










const getRecentCoursesService = async (userId) => {

  if (!userId) {
    throw new Error("User ID is required");
  }

  const courses = await findRecentCoursesByUser(userId);

  return courses.map(course => ({
    courseId: course._id,
    courseTitle: course.title,
    courseDescription: course.description,
  }));
};





const getUserCourseService = async (userId) => {

  if (!userId) {
    throw new Error("User ID is required");
  }

  const courses = await findRecentCoursesByUser(userId, 7);

  return courses.map(course => ({
    courseId: course._id,
    courseTitle: course.title,
    courseDescription: course.description,
  }));
};







const getCourseDetailsWithProgressService = async (courseId, userId) => {
  if (!courseId || !userId) {
    throw new Error("Course ID and User ID are required");
  }

  const course = await findById(courseId); // now populates modules + lessons
  if (!course) {
    throw new Error("Course not found");
  }

  // Find first incomplete module
  let currentModuleIndex = 1;
  let currentLessonIndex = 1;

  let found = false;
  for (const mod of course.modules) {
    for (const lesson of mod.lessons) {
      if (!lesson.isCompleted) {
        currentModuleIndex = mod.moduleIndex;
        currentLessonIndex = lesson.lessonIndex;
        found = true;
        break;
      }
    }
    if (found) break;
  }

  // All lessons completed — point to the last lesson
  if (!found && course.modules.length > 0) {
    const lastMod = course.modules[course.modules.length - 1];
    currentModuleIndex = lastMod.moduleIndex;
    const lastLesson = lastMod.lessons[lastMod.lessons.length - 1];
    currentLessonIndex = lastLesson ? lastLesson.lessonIndex : 1;
  }

  return {
    course,
    progress: {
      currentModule: currentModuleIndex,
      currentLesson: currentLessonIndex,
    },
  };
};


const completeLessonService = async ({
  moduleId,
  lessonId,
}) => {
  if (!moduleId || !lessonId) {
    throw new Error("Missing required parameters");
  }

  const course =
    await markLessonCompleted({
      moduleId,
      lessonId,
    });

  if (!course) {
    throw new Error("Course not found");
  }

  return {
    message: "Lesson marked as completed",
  };
};


const getLessonContentService = async ({
  moduleId,
  lessonId,
}) => {
  const result =
    await findLessonForUser({
      moduleId,
      lessonId,
    });

  if (!result) {
    throw new Error("Lesson not found");
  }

  const lesson = result;

  return {
    lesson: {
      title: lesson.title,
      description: lesson.briefDescription,
      ...lesson.content,
      hinglishContent: lesson.hinglishContent,
      isCompleted: lesson.isCompleted,
      lessonIndex: lesson.lessonIndex,
      module: lesson.module,
      _id: lesson._id,
    },
    module: {
      title: "Learning Module", // Fallback title
      moduleIndex: lesson.moduleIndex || 0,
    },
  };
};

const getYouTubeVideosService = async (query) => {
  try {
    return await getYouTubeVideos(query);
  } catch (error) {
    throw error;
  }
};

const checkLessonExistsService = async ({
  moduleId,
  lessonId,
}) => {
  const exists =
    await checkLessonExistsForUser({
      moduleId,
      lessonId,
    });

  return { exists };
};



const saveLessonService = async (
  moduleId,
  lessonId,
  lesson
) => {
  let actualLesson = lesson;



  if (!moduleId || !lessonId || !actualLesson) {
    throw new Error("Missing required parameters for saving lesson");
  }

  let lessonPayload = {};

  if (actualLesson && actualLesson.data) {
    lessonPayload.content = actualLesson.data;
  } else if (actualLesson && actualLesson.content) {
    lessonPayload = actualLesson;
  } else {
    lessonPayload.content = actualLesson;
  }


  const savedLesson = await saveLesson(
    moduleId,
    lessonId,
    lessonPayload
  );

  if (!savedLesson) {
    throw new Error("Failed to save lesson (Course/Module/Lesson not found)");
  }


  return savedLesson;
};

const saveHinglishContentService = async (moduleId, lessonId, content) => {
  if (!moduleId || !lessonId || !content) {
    throw new Error("Missing parameters for saving Hinglish content");
  }
  return await saveHinglishContent(moduleId, lessonId, content);
};

module.exports = {
  saveCourseOutlineToDBService, getRecentCoursesService, getCourseDetailsWithProgressService,
  completeLessonService,
  getLessonContentService,
  checkLessonExistsService,
  saveLessonService,
  getYouTubeVideosService,
  saveHinglishContentService,
  getUserCourseService,
};