const {
  findById,
  findCourseForUser,
  saveCourseOutlineToDB,
  findRecentCoursesByUser,
  findLessonForUser,
  checkLessonExistsForUser,
  saveLesson,
  saveHinglishContent,
  searchVectorDB,
  getLesson,
  updateLessonStatus,
  completeLessonForUser,
} = require("../repository/course.repository");

const { addLessonToGenerationQueue } = require("../utils/helper");

const { getYouTubeVideos } = require("../repository/YouTube.repository");

const mongoose = require("mongoose");
const Course = require("../models/course");
const Module = require("../models/module");
const Lesson = require("../models/lesson");
const { getCourseCache, setCourseCache, invalidateCourseCache } = require("./cache.service");
const CourseTemplate = require("../models/course-template");
const Enrollment = require("../models/enrollment");

const { generateEmbedding } = require("./ai_embeding_service");
const {
  generateOutlineService,
  intentGenerationService,
  generateLessonService,
} = require("./course.generate.service");




const saveCourseOutlineToDBService = async (
  outline,
  userId,
  intent,
  embedding,
  prompt,
) => {
  if (!outline?.course || !outline?.modules) {
    throw new Error("Invalid course outline structure");
  }

  const session = await mongoose.startSession();

  try {
    session.startTransaction();

    const { course, modules } = outline;

    //-------------------------------------
    // Create Course
    //-------------------------------------

    const [template] = await CourseTemplate.create([
      {
        title: course.title || "Untitled Course",
        description: course.description || "Course generated by AI",
        learningIntent: intent,
        outline,
        embedding,
      },
    ], { session });

    const [createdCourse] = await Course.create(
      [
        {
          title: course.title || "Untitled Course",

          description: course.description || "Course generated by AI",

          userId,

          learningIntent: {
            topic: intent.topic,
            goal: intent.goal,
            level: intent.level,
            targetRole: intent.targetRole,

            canonicalQuery: intent.canonicalQuery,

            confidence: intent.confidence,
          },

          embedding,

          generatedFromPrompt: prompt,
          templateId: template._id,
        },
      ],
      { session },
    );

    //-------------------------------------
    // Create Modules + Lessons
    //-------------------------------------

    for (const moduleData of modules) {
      const [createdModule] = await Module.create(
        [
          {
            moduleIndex: moduleData.moduleIndex,

            title: moduleData.title,

            description: moduleData.description,
            course: createdCourse._id,
          },
        ],
        { session },
      );

      //-------------------------------------
      // Build Lessons
      //-------------------------------------

      const lessonDocuments = moduleData.lessons.map((lesson) => ({
        lessonIndex: lesson.lessonIndex,

        title: lesson.title,

        realWorldProblem: lesson.realWorldProblem,

        learnerTakeaway: lesson.learnerTakeaway,

        completionCriteria: lesson.completionCriteria,

        briefDescription: lesson.briefDescription,

        estimatedMinutes: lesson.estimatedMinutes || 30,
        skillTags: lesson.skillTags || [],
        handsOnTask: lesson.handsOnTask,
        resources: lesson.resources || [],

        module: createdModule._id,

        content: null,

        isGenerated: "PENDING",
      }));

      let createdLessons = [];
      if (lessonDocuments.length > 0) {
        createdLessons = await Lesson.insertMany(lessonDocuments, { session });
      }

      // Add lesson IDs to module.lessons
      createdModule.lessons = createdLessons.map(l => l._id);
      await createdModule.save({ session });

      // Add module ID to course.modules
      createdCourse.modules.push(createdModule._id);
    }

    // Save course with modules
    await createdCourse.save({ session });
    await Enrollment.create([{ userId, templateId: template._id, courseId: createdCourse._id }], { session });

    await session.commitTransaction();

    // Fetch the full course with populated modules/lessons to return
    const fullCourse = await Course.findById(createdCourse._id)
      .populate({
        path: "modules",
        populate: { path: "lessons" },
      })
      .session(session)
      .lean();

    return fullCourse;
  } catch (error) {
    await session.abortTransaction();

    throw error;
  } finally {
    session.endSession();
  }
};

const getRecentCoursesService = async (userId) => {
  console.log("\n\n\n\n s ***************************\n\n\n");

  if (!userId) {
    throw new Error("User ID is required");
  }

  const courses = await findRecentCoursesByUser(userId);

  return courses.map((course) => ({
    courseId: course._id,
    courseTitle: course.title,
    courseDescription: course.description,
  }));
};

const getUserCourseService = async (userId) => {
  if (!userId) {
    throw new Error("User ID is required");
  }

  const courses = await findRecentCoursesByUser(userId, 100); // Get up to 100 courses

  return courses.map((course) => ({
    courseId: course._id,
    courseTitle: course.title,
    courseDescription: course.description,
  }));
};

const stream = (res, message, extra = {}) => {
  res.write(
    `data: ${JSON.stringify({
      message,
      ...extra,
    })}\n\n`,
  );
};


// Send course via SSE
const sendCourse = (res, course) => {
  try {
    if (!course) {
      res.write(
        `data: ${JSON.stringify({
          type: "ERROR",
          message: "Course data not found",
        })}\n\n`,
      );
      return res.end();
    }

    res.write(
      `data: ${JSON.stringify({
        type: "SUCCESS",
        message: "Course generated successfully",
        course: {
          _id: course._id,
          title: course.title,
          description: course.description,
          learningIntent: course.learningIntent,
        },
      })}\n\n`,
    );

    return res.end();
  } catch (error) {
    console.error("sendCourse error:", error);
    res.write(
      `data: ${JSON.stringify({
        type: "ERROR",
        message: "Error sending course data",
      })}\n\n`,
    );
    return res.end();
  }
};



const generateCourseFlow = async (prompt, res, userId) => {
  try {
    if (!prompt || !userId) {
      stream(res, "Error: Missing prompt or userId");
      return res.end();
    }

    stream(res, "🎯 Extracting learning intent from your prompt...");

    const intent = await intentGenerationService({ prompt });

    if (!intent || !intent.canonicalQuery) {
      throw new Error("Failed to extract learning intent");
    }

    stream(res, "🔍 Generating semantic embedding...");

    const embedding = await generateEmbedding(intent.canonicalQuery);

    stream(res, "🔎 Searching for similar existing courses...");

    const similar = await searchVectorDB(embedding);

    if (similar && similar.userId?.toString() === userId.toString() && similar.score > 0.9 && similar._id) {
      console.log(
        `✅ Found existing course with ${(similar.score * 100).toFixed(1)}% similarity`,
      );

      stream(
        res,
        `✨ Found a similar course (${(similar.score * 100).toFixed(1)}% match)! Returning existing course...`,
      );

      // Get the full course with modules/lessons populated
      const fullSimilarCourse = await findById(similar._id);
      return sendCourse(res, fullSimilarCourse);
    }

    console.log(
      `❌ No similar course found (best match: ${similar ? (similar.score * 100).toFixed(1) : 0}%)`,
    );

    stream(
      res,
      "🚀 No similar course found. Generating brand new course structure...",
    );

    const course = await generateOutlineService(intent);

    if (!course) {
      throw new Error("Failed to create new course");
    }

    stream(res, "✅ Course generated successfully!");

    const savedCourse = await saveCourseOutlineToDBService(
      course,
      userId,
      intent,
      embedding,
      prompt,
    );

    stream(res, "✅ Course saved successfully!");

    // Lazy queue initialization: lessons are queued on-demand when user requests them
    // No automatic queueing to prevent premature processing

    return sendCourse(res, savedCourse);

  } catch (error) {
    console.error("❌ generateCourseFlow error:", error);

    res.write(
      `data: ${JSON.stringify({
        type: "ERROR",
        message: error.message || "Course generation failed",
        error: process.env.NODE_ENV === "development" ? error.stack : undefined,
      })}\n\n`,
    );

    return res.end();
  }
};

const getCourseDetailsWithProgressService = async (courseId, userId) => {
  if (!courseId || !userId) {
    throw new Error("Course ID and User ID are required");
  }

  let course = await getCourseCache(courseId, userId);
  if (!course) {
    course = await findCourseForUser(courseId, userId);
    if (course) await setCourseCache(courseId, userId, course);
  }
  if (!course) {
    throw new Error("Course not found");
  }

  // Find first incomplete module
  let currentModuleIndex = 1;
  let currentLessonIndex = 1;

  let found = false;
  for (const mod of course.modules) {
    for (const lesson of mod.lessons) {
      if (!lesson.isCompleted) {
        currentModuleIndex = mod.moduleIndex;
        currentLessonIndex = lesson.lessonIndex;
        found = true;
        break;
      }
    }
    if (found) break;
  }

  // All lessons completed — point to the last lesson
  if (!found && course.modules.length > 0) {
    const lastMod = course.modules[course.modules.length - 1];
    currentModuleIndex = lastMod.moduleIndex;
    const lastLesson = lastMod.lessons[lastMod.lessons.length - 1];
    currentLessonIndex = lastLesson ? lastLesson.lessonIndex : 1;
  }

  return {
    course,
    progress: {
      currentModule: currentModuleIndex,
      currentLesson: currentLessonIndex,
    },
  };
};

const completeLessonService = async ({ moduleId, lessonId, userId, quizScore }) => {
  if (!moduleId || !lessonId) {
    throw new Error("Missing required parameters");
  }

  const lesson = await completeLessonForUser({
    moduleId,
    lessonId,
    userId,
    quizScore,
  });

  if (!lesson) {
    throw new Error("Lesson not found");
  }

  const moduleData = await Module.findById(moduleId).select("course").lean();
  if (moduleData) {
    await Enrollment.updateOne(
      { userId, courseId: moduleData.course },
      { $pull: { progress: { lessonId } } },
    );
    await Enrollment.updateOne(
      { userId, courseId: moduleData.course },
      { $push: { progress: { lessonId, completedAt: lesson.completedAt, quizScore: lesson.quizScore } } },
    );
  }
  await invalidateCourseCache(moduleData?.course, userId);

  return {
    message: "Lesson marked as completed",
  };
};

const getLessonContentService = async ({ moduleId, lessonId, userId }) => {
  const result = await findLessonForUser({
    moduleId,
    lessonId,
    userId,
  });

  if (!result) {
    throw new Error("Lesson not found");
  }

  const lesson = result;

  return {
    lesson: {
      title: lesson.title,
      description: lesson.briefDescription,
      ...lesson.content,
      hinglishContent: lesson.hinglishContent,
      estimatedMinutes: lesson.estimatedMinutes,
      skillTags: lesson.skillTags,
      handsOnTask: lesson.handsOnTask,
      resources: lesson.resources,
      retrievalCitations: lesson.retrievalCitations || [],
      quizScore: lesson.quizScore,
      isCompleted: lesson.isCompleted,
      lessonIndex: lesson.lessonIndex,
      module: lesson.module,
      _id: lesson._id,
    },
    module: {
      title: "Learning Module", // Fallback title
      moduleIndex: lesson.moduleIndex || 0,
    },
  };
};


const getYouTubeVideosService = async (query) => {
  try {
    return await getYouTubeVideos(query);
  } catch (error) {
    throw error;
  }
};


const checkLessonExistsService = async ({ lessonId, moduleId, userId }) => {
  const lesson = await findLessonForUser({ lessonId, moduleId, userId });
  const exists = Boolean(lesson?.content);
  return { exists };
};


const saveLessonService = async (moduleId, lessonId, lesson, userId) => {
  let actualLesson = lesson;

  if (!moduleId || !lessonId || !actualLesson) {
    throw new Error("Missing required parameters for saving lesson");
  }

  if (userId) {
    const ownedLesson = await findLessonForUser({ moduleId, lessonId, userId });
    if (!ownedLesson) throw new Error("Lesson not found");
  }

  let lessonPayload = {};

  if (actualLesson && actualLesson.data) {
    lessonPayload.content = actualLesson.data;
  } else if (actualLesson && actualLesson.content) {
    lessonPayload = actualLesson;
  } else {
    lessonPayload.content = actualLesson;
  }

  const savedLesson = await saveLesson(moduleId, lessonId, lessonPayload);

  if (!savedLesson) {
    throw new Error("Failed to save lesson (Course/Module/Lesson not found)");
  }

  return savedLesson;
};

const saveHinglishContentService = async (moduleId, lessonId, content) => {
  if (!moduleId || !lessonId || !content) {
    throw new Error("Missing parameters for saving Hinglish content");
  }
  return await saveHinglishContent(moduleId, lessonId, content);
};



const lessonGenerationFlow = async (lessonId, res, userId) => {
  try {
    if (!lessonId) {
      stream(res, "❌ Error: Lesson ID is missing");
      return res.end();
    }

    stream(res, "🔍 Fetching lesson details...");

    // Fetch lesson from DB
    const lesson = await getLesson(lessonId);
    if (!lesson) {
      throw new Error("Lesson not found");
    }

    // Verify ownership before exposing cached content or queue state.
    const Module = require("../models/module");
    const moduleData = await Module.findById(lesson.module);
    if (!moduleData) {
      throw new Error("Module not found");
    }

    const course = await findCourseForUser(moduleData.course, userId);
    if (!course) {
      throw new Error("Course not found");
    }

    // Check if lesson already generated
    if (lesson.isGenerated === "GENERATED" && lesson.content) {
      stream(res, "✅ Lesson already generated. Retrieving from cache...");
      stream(
        res,
        "✅ Lesson loaded successfully!",
        {
          type: "SUCCESS",
          lesson: {
            _id: lesson._id,
            title: lesson.title,
            description: lesson.briefDescription,
            content: lesson.content,
            youtubeQuery: lesson.youtubeQuery,
            isGenerated: lesson.isGenerated,
          },
        }
      );
      return res.end();
    }

    // Check if lesson is already being generated or in queue
    if (lesson.isGenerated === "GENERATING") {
      stream(res, "⏳ Lesson is already being generated...");
      return res.end();
    }

    // Add lesson to generation queue (user explicitly requested it)
    stream(res, "📋 Adding lesson to generation queue...");
    await addLessonToGenerationQueue(
      moduleData.course.toString(),
      moduleData._id.toString(),
      lessonId
    );

    // Keep connection open and poll until lesson is generated or timeout
    stream(res, "⏳ Waiting for lesson generation to complete...");
    
    let pollingCount = 0;
    const maxPollingCount = 60; // 60 seconds max
    const pollIntervalMs = 1000; // Check every second

    const pollForLesson = async () => {
      while (pollingCount < maxPollingCount) {
        const updatedLesson = await getLesson(lessonId);
        
        if (updatedLesson.isGenerated === "GENERATED" && updatedLesson.content) {
          // Lesson completed successfully
          stream(
            res,
            "✅ Lesson generated and saved successfully!",
            {
              type: "SUCCESS",
              lesson: {
                _id: updatedLesson._id,
                title: updatedLesson.title,
                description: updatedLesson.briefDescription,
                content: updatedLesson.content,
                youtubeQuery: updatedLesson.youtubeQuery,
                isGenerated: updatedLesson.isGenerated,
              },
            }
          );
          return res.end();
        }

        if (updatedLesson.isGenerated === "FAILED") {
          throw new Error("Lesson generation failed");
        }

        // Still waiting...
        pollingCount++;
        await new Promise(resolve => setTimeout(resolve, pollIntervalMs));
      }

      // Timeout
      throw new Error("Lesson generation timed out. Please try again later.");
    };

    await pollForLesson();

  } catch (error) {
    console.error("❌ lessonGenerationFlow error:", error);
    res.write(
      `data: ${JSON.stringify({
        type: "ERROR",
        message: error.message || "Lesson generation failed",
        error:
          process.env.NODE_ENV === "development" ? error.stack : undefined,
      })}\n\n`
    );
    return res.end();
  }
};



module.exports = {
  saveCourseOutlineToDBService,
  getRecentCoursesService,
  getCourseDetailsWithProgressService,
  completeLessonService,
  getLessonContentService,
  checkLessonExistsService,
  saveLessonService,
  getYouTubeVideosService,
  saveHinglishContentService,
  getUserCourseService,
  generateCourseFlow,
  lessonGenerationFlow,
};
