import React, { forwardRef } from "react";

const LessonPDF = forwardRef(({ course, lesson, youtubeVideos }, ref) => {
  if (!lesson) return null;

  return (
    <div
      ref={ref}
      style={{
        padding: "40px",
        fontFamily: "Arial, sans-serif",
        color: "#111",
      }}
    >
      <h1 style={{ textAlign: "center" }}>{course?.title}</h1>
      <p style={{ textAlign: "center", marginBottom: "30px" }}>
        {course?.description}
      </p>

      <hr />

      <h2>{lesson.title}</h2>

      {lesson.introduction && (
        <>
          <h3>Introduction</h3>
          <p>{lesson.introduction}</p>
        </>
      )}

      {lesson.mainPoints?.length > 0 && (
        <>
          <h3>Core Concepts</h3>
          {lesson.mainPoints.map((p, i) => (
            <div key={i} style={{ marginBottom: "16px" }}>
              <strong>{p.heading}</strong>
              <p>{p.explanation}</p>
            </div>
          ))}
        </>
      )}

      {lesson.examples?.length > 0 && (
        <>
          <h3>Examples</h3>
          {lesson.examples.map((ex, i) => (
            <div key={i}>
              <strong>{ex.title}</strong>
              <pre style={{ whiteSpace: "pre-wrap" }}>{ex.content}</pre>
            </div>
          ))}
        </>
      )}

      {lesson.mcqs?.length > 0 && (
        <>
          <h3>Quiz (With Answers)</h3>
          {lesson.mcqs.map((q, i) => (
            <div key={i} style={{ marginBottom: "18px" }}>
              <p>
                <strong>Q{i + 1}:</strong> {q.question}
              </p>
              <ul>
                {q.options.map((opt, idx) => (
                  <li
                    key={idx}
                    style={{
                      fontWeight:
                        idx === q.answerIndex ? "bold" : "normal",
                    }}
                  >
                    {opt}
                  </li>
                ))}
              </ul>
              <p>
                <em>Explanation:</em> {q.explanation}
              </p>
            </div>
          ))}
        </>
      )}

      {youtubeVideos?.length > 0 && (
        <>
          <h3>Video Resources</h3>
          <ul>
            {youtubeVideos.map((v) => (
              <li key={v.videoId}>
                <a href={v.videoUrl}>{v.title}</a> — {v.channel}
              </li>
            ))}
          </ul>
        </>
      )}

      <hr />
      <p style={{ textAlign: "center", fontSize: "12px" }}>
        Generated by Text-To-Learn
      </p>
    </div>
  );
});

export default LessonPDF;